# 工作流名称，不设置的话默认取配置文件名
name: Deploy Vue Project to gh-pages
# 指定触发 workflow 的条件
# 指定触发事件时，可以限定分支或标签
# 当前是 只有 master分支上触发 push 事件时才执行工作流任务
on: 
  push:
    branches:
      - main
# 工作流执行的一个或多个任务
jobs:
  # 任务名称
  build-and-deploy:
    # 任务运行的容器类型（虚拟机环境）
    runs-on: ubuntu-latest
    # 任务执行的步骤
    steps:
      # 步骤名称
      - name: Checkout the repository
        # 使用的操作 actions，可以使用公共仓库，本地仓库，别人的仓库的action
        # 拉取代码
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # 根据你的项目需求选择 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTION_SECRET }}
          publish_dir: ./docs  # 根据你的打包输出目录进行调整

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Modify index.html and add 404.html
        run: |
          cd gh-pages
          
          # 修改 index.html 在 </head> 前添加脚本
          sed -i '/<\/head>/i <script>(function(l){if(l.search[1]==="/"){var decoded=l.search.slice(1).split("&").map(function(s){return s.replace(/~and~/g,"&")}).join("?");window.history.replaceState(null,null,l.pathname.slice(0,-1)+decoded+l.hash)}}(window.location))</script>' index.html
  
          # 添加压缩后的 404.html 文件
          echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Single Page Apps for GitHub Pages</title><script type="text/javascript">var pathSegmentsToKeep=0;var l=window.location;l.replace(l.protocol+\"//\"+l.hostname+(l.port?\":\"+l.port:\"\")+l.pathname.split(\"/\").slice(0,1+pathSegmentsToKeep).join(\"/\")+\"/?/\"+l.pathname.slice(1).split(\"/\").slice(pathSegmentsToKeep).join(\"/\").replace(/&/g,\"~and~\")+(l.search?\"&\"+l.search.slice(1).replace(/&/g,\"~and~\"):\"\")+l.hash);</script></head><body></body></html>' > 404.html
  
      - name: Commit and push changes
        run: | 
          cd gh-pages
          git config --global user.email "chengfayang@henu.edu.cn"
          git config --global user.name "Moipha"
          git add index.html 404.html
          git commit -m "Update index.html and add 404.html"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 


          

